version: "3"
services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`coyotiv-barnali-smollich.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    ports:
      - 8080
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      # MONGODB_USERNAME=root
      # MONGODB_PASSWORD=lY4MNHFiV6CNBkMz
      # MONGODB_DATABASE=FamilyDiary
      - MONGODB_CONNECTION_STRING=mongodb://mongo/coyotiv-barnali-smollich
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=(Host(`coyotiv-barnali-smollich.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/socket`)))"
      - "traefik.http.routers.backend.entrypoints=web"
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27018:27017
    # volumes:
    # - ./data:/data
  load-balancer:
    image: traefik:v2.
    container_name: load-balancer
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
