version: '3'
services:
  app:
    image: coyotiv-barnali-smollich
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # MONGODB_USERNAME=root
      # MONGODB_PASSWORD=lY4MNHFiV6CNBkMz
      # MONGODB_DATABASE=FamilyDiary
      - MONGODB_CONNECTION_STRING=mongodb://mongo/coyotiv-barnali-smollich
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
    # volumes:
    # - ./data:/data
